name: Daily Commit

on:
  schedule:
    - cron: '00 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger


jobs:
  update-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for proper merging

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Pull latest changes
        run: |
          git pull origin master --rebase || echo "No need to pull"

      - name: Make changes
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Daily commit on $(date)" || echo "No changes to commit"
          git push origin main

      - name: 23f2002600@ds.study.iitm.ac.in
        run: echo "Commit made by GitHub Actions"
